groups:
  - name: flask_app_alerts
    rules:
      - alert: AppDown
        expr: up{job="flask-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "L'application Flask est down"
          description: "flask-app n'est plus accessible depuis plus d'1 minute."

      - alert: HighErrorRate
        expr: rate(flask_http_request_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Taux d'erreurs 5xx élevé"
          description: "Plus de 10% des requêtes retournent une erreur 5xx."
