{
 "title": "Flask App Dashboard",
 "description": "Flask App Monitoring Dashboard",
 "tags": [
  "devops",
  "flask",
  "monitoring"
 ],
 "panels": [
  {
   "title": "Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "{{method}} {{status}} {{path}}"
    }
   ]
  },
  {
   "title": "Latence moyenne",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[1m]) / rate(flask_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Taux d'erreurs 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{status=~\"5..\"}[1m])",
     "legendFormat": "Erreurs 5xx/s"
    }
   ]
  },
  {
   "title": "Total requêtes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(flask_http_request_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Uptime App",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"flask-app\"}",
     "legendFormat": "Up"
    }
   ]
  }
 ]
}